name: Sample Dependent Workflow

on:
  workflow_run:
    workflows: ["Sample Workflow"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Test workflow job is triggered after Sample Workflow"
