name: "Sample Flake8"

on:
  push:
    branches:
      - main

jobs:
  flake8:
    name: flake8
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: python version
      run: python --version

    - name: Run flake8
      run: flake8 .

    - name: flake8 Success
      run: echo "flake8 Evaluation Success"
