name: "Sample Flake8"

on:
  push:
    branches:
      - main

jobs:
  flake8:
    name: flake8
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run flake8
      run: flake8 .

    - name: ShellCheck Success
      run: echo "ShellCheck Evaluation Success"
