name: "Sample gitleaks"

on:
  push:
    branches:
      - main

jobs:
  gitleaks:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: install gitleaks
      run: |
        wget -qO- "https://github.com/gitleaks/gitleaks/releases/download/v8.26.0/gitleaks_8.26.0_linux_x64.tar.gz" | tar -xz
        cp "gitleaks" /usr/local/bin
        gitleaks --version

    - name: Run Gitleaks
      run: gitleaks detect --source . --no-git -v
