name: "Sample gitleaks"

on:
  push:
    branches:
      - main

jobs:
  gitleaks:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: gitleaks
      uses: gitleaks/gitleaks-action@v2
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE}}
