
name: "Sample Job"

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: run
      run: echo "Running job1"
  job2:
    needs: [job1]
    if: needs.job1.result != 'success'
    runs-on: ubuntu-latest
    steps:
    - name: run
      run: echo "Running job2"
  job3:
    needs: [job1]
    runs-on: ubuntu-latest
    steps:
    - name: run
      run: echo "Running job3"
  job4:
    needs: [job1]
    runs-on: ubuntu-latest
    steps:
    - name: run
      run: echo "Running job4"
  job5:
    needs: [job1, job2, job3, job4]
    runs-on: ubuntu-latest
    if: ${{ always() &&
        needs.job2.result != 'failure' &&
        needs.job3.result != 'failure' &&
        needs.job4.result != 'failure' &&
      (
        needs.job2.result == 'success' ||
        needs.job3.result == 'success' ||
        needs.job4.result == 'success'
      )
     }}
    steps:
    - name: run
      run: echo "Running job5"
  job6:
    needs: [job1, job5]
    runs-on: ubuntu-latest
    steps:
    - name: run
      run: echo "Running job6"


