name: "Sample PSScriptAnalyzer"

on:
  push:
    branches:
      - main

jobs:
  PSScriptAnalyzer:
    name: PSScriptAnalyzer
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install PSScriptAnalyzer
      run: |
        Install-Module -Name PSScriptAnalyzer
        $PSVersionTable.PSVersion

    - name: Run PSScriptAnalyzer
      run: Invoke-ScriptAnalyzer -Path scripts/
