name: "Sample pylint"

on:
  push:
    branches:
      - main

jobs:
  flake8:
    name: pylint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install pylint
      run: pip install pylint

    - name: Run pylint
      run: pylint scripts/tanium.py

    - name: pylint Success
      run: echo "pylint Evaluation Success"
