name: Sample Workflow

run-name: ${{ github.actor }} is running Sample Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  sample-job:
    runs-on: ubuntu-latest
    steps:
      - name: Sample Step
        run: |
          echo "This is a sample job."
