name: Sample Workflow

run-name: ${{ github.actor }} is running Sample Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      runner_name:
        description: 'Who is running this workflow?'
        required: true
        default: 'Sireesha'
  
jobs:
  sample-job:
    runs-on: ubuntu-latest
    steps:
      - name: Sample Step
        run: |
          echo "This is a sample job ${{ github.event.inputs.runner_name }}"
  conditional-job:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Conditional Check
        run: |
          echo "This conditional job runs only when push to main branch"
  
          
          
