name: Sample Workflow

run-name: ${{ github.actor }} is running Sample Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      actor_name:
        Description: 'Who is running this workflow?'
        Required: true
        Default: Sireesha
  
jobs:
  sample-job:
    runs-on: ubuntu-latest
    steps:
      - name: Sample Step
        run: |
          echo "This is a sample job ${{ github.event.inputs.actor_name }}"
  conditional-job:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Conditional Check
        run: |
          echo "This conditional job runs only when push to main branch"
  
          
          
