name: "Sample ShellCheck"

on:
  push:
    branches:
      - main

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Shellcheck verion
      run: shellcheck --version
    - name: Run ShellCheck
      run: find . -type f -name "*.sh" -exec shellcheck {} +
